/**
 * ASCEND game-engine — zod mirrors of the contract in `./types.ts`.
 *
 * These exist for exactly one job: validating UNTRUSTED data at the backend boundary
 * (HTTP bodies, device payloads, rows read back from storage) before it reaches a pure
 * function that assumes it is well-formed. The engine's own internals do not re-validate;
 * they trust the types, which is only safe because the boundary does not.
 *
 * `mobile-app` must NOT import this module — it imports `@ascend/game-engine/types`
 * instead, so zod never enters the app bundle.
 *
 * NOTHING HERE IS DERIVED BY HAND TWICE. The enums are built from the `as const` lists in
 * `./types.ts`, the stat shape is built by iterating `STAT_KEYS`, and the drift guards at
 * the bottom of this file fail `tsc` if any schema stops mirroring its interface.
 *
 * Unknown keys are STRIPPED, not rejected (zod's default). A newer mobile build sending a
 * field this engine version does not know about is forward compatibility, not an error.
 */
import { z } from 'zod';

import {
  BATTLE_ACTORS,
  BATTLE_EVENT_TYPES,
  BATTLE_OUTCOMES,
  HERO_CLASSES,
  REWARD_KINDS,
  STAT_KEYS,
  TRUST_TIERS,
  type ActivityInput,
  type BattleEvent,
  type BattleLog,
  type EngineContext,
  type Hero,
  type RewardEntry,
  type StatBlock,
  type StatKey,
} from './types';

/* -------------------------------------------------------------------------- *
 * Named validation bounds.
 *
 * These are boundary sanity limits, not game tuning — tuning lives in
 * `src/rewards/constants.ts` and `src/battle/constants.ts` per the repo invariants.
 * They are named and exported anyway so no bare number appears in the rules below and
 * so the backend can reuse the same limits in its own input forms.
 * -------------------------------------------------------------------------- */

/** Lowest heart rate the engine will accept as real, bpm. Below this it is sensor noise or a dead sensor. */
export const HR_MIN_BPM = 20;

/** Highest heart rate the engine will accept as real, bpm. Above this it is a sensor artefact. */
export const HR_MAX_BPM = 250;

/** Lowest accepted `proteinAdequacy`. */
export const PROTEIN_ADEQUACY_MIN = 0;

/** Highest accepted `proteinAdequacy`. */
export const PROTEIN_ADEQUACY_MAX = 1;

/**
 * The one true shape of `EngineContext.localDate`: an ISO calendar date, `YYYY-MM-DD`.
 * Exported so the backend validates the value it computes with the same rule the engine
 * accepts it by. Intentionally a shape check only — it does not reject the 31st of
 * February, because the caller owns the calendar and this is a boundary sanity check.
 */
export const LOCAL_DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

/* -------------------------------------------------------------------------- *
 * Reusable numeric primitives.
 *
 * EP, XP, gold and stats are INTEGERS by repo invariant: folding float deltas gives
 * order-dependent totals, which silently corrupts replay. `.int()` also rejects
 * `Infinity` and `NaN`, so these are total sanity checks, not just sign checks.
 * -------------------------------------------------------------------------- */

/** A whole number, either sign. */
const IntSchema = z.number().int();

/** A whole number >= 0. */
const NonNegativeIntSchema = z.number().int().nonnegative();

/** A whole number > 0. */
const PositiveIntSchema = z.number().int().positive();

/** A finite real >= 0 — for measurements that legitimately are not whole (metres, kcal). */
const NonNegativeFiniteSchema = z.number().nonnegative().finite();

/** A plausible heart rate in bpm. Not forced to an integer: devices report averages. */
const HeartRateSchema = z.number().finite().min(HR_MIN_BPM).max(HR_MAX_BPM);

/** A non-empty identifier or label. Empty strings are almost always a serialisation bug. */
const NonEmptyStringSchema = z.string().min(1);

/* -------------------------------------------------------------------------- *
 * Enum schemas, built from the canonical `as const` lists.
 * -------------------------------------------------------------------------- */

/** Mirrors `TrustTier`. */
export const TrustTierSchema = z.enum(TRUST_TIERS);

/** Mirrors `HeroClass`. */
export const HeroClassSchema = z.enum(HERO_CLASSES);

/** Mirrors `RewardKind`. */
export const RewardKindSchema = z.enum(REWARD_KINDS);

/** Mirrors `BattleActor`. */
export const BattleActorSchema = z.enum(BATTLE_ACTORS);

/** Mirrors `BattleEventType`. */
export const BattleEventTypeSchema = z.enum(BATTLE_EVENT_TYPES);

/** Mirrors `BattleOutcome`. */
export const BattleOutcomeSchema = z.enum(BATTLE_OUTCOMES);

/* -------------------------------------------------------------------------- *
 * Object schemas
 * -------------------------------------------------------------------------- */

/**
 * Mirrors `StatBlock`.
 *
 * The shape is generated by iterating `STAT_KEYS` rather than typed out again, so a new
 * stat becomes required here automatically and a stat block can never be validated with
 * a key missing. Stats are non-negative integers: they are earned and never spent.
 */
const statShape = Object.fromEntries(
  STAT_KEYS.map((key) => [key, NonNegativeIntSchema]),
) as { [K in StatKey]: typeof NonNegativeIntSchema };

/** Mirrors `StatBlock` — all six stats required, each a non-negative integer. */
export const StatBlockSchema = z.object(statShape);

/**
 * Mirrors `ActivityInput`. The primary untrusted payload: this is what arrives from a
 * phone, so every field is treated as hostile until proven otherwise.
 */
export const ActivityInputSchema = z
  .object({
    activityType: NonEmptyStringSchema,
    durationSec: PositiveIntSchema,
    startedAtMs: NonNegativeIntSchema,
    endedAtMs: NonNegativeIntSchema,
    trustTier: TrustTierSchema,
    distanceM: NonNegativeFiniteSchema.optional(),
    activeKcal: NonNegativeFiniteSchema.optional(),
    avgHr: HeartRateSchema.optional(),
  })
  .refine((activity) => activity.endedAtMs >= activity.startedAtMs, {
    message: 'endedAtMs must not be earlier than startedAtMs',
    path: ['endedAtMs'],
  });

/**
 * Mirrors `EngineContext`.
 *
 * `localDate` is validated, never computed: the engine has no clock and the training-day
 * bucket is the caller's product decision (see the doc comment on `EngineContext`).
 * Validating its shape here is the engine's only defence against a caller passing a
 * timestamp, an empty string, or a locale-formatted date into a cap key.
 */
export const EngineContextSchema = z.object({
  timezone: NonEmptyStringSchema,
  localDate: z
    .string()
    .regex(LOCAL_DATE_PATTERN, 'localDate must be an ISO calendar date, YYYY-MM-DD'),
  epToday: NonNegativeIntSchema,
  epThisWeek: NonNegativeIntSchema,
  maxHr: HeartRateSchema.optional(),
  restingHr: HeartRateSchema.optional(),
  proteinAdequacy: z
    .number()
    .finite()
    .min(PROTEIN_ADEQUACY_MIN)
    .max(PROTEIN_ADEQUACY_MAX)
    .optional(),
});

/** Mirrors `Hero`. Levels are 1-based; xp and gold are non-negative integers. */
export const HeroSchema = z.object({
  id: NonEmptyStringSchema,
  name: NonEmptyStringSchema,
  heroClass: HeroClassSchema,
  level: PositiveIntSchema,
  xp: NonNegativeIntSchema,
  gold: NonNegativeIntSchema,
  stats: StatBlockSchema,
});

/**
 * Mirrors `RewardEntry`.
 *
 * `amount` is a SIGNED integer on purpose: the ledger is append-only, so a correction or
 * a decay is expressed as a negative row rather than by editing history.
 */
export const RewardEntrySchema = z.object({
  kind: RewardKindSchema,
  amount: IntSchema,
  engineVersion: NonEmptyStringSchema,
});

/**
 * Mirrors `BattleEvent`.
 *
 * HP values are non-negative: the simulator clamps at zero, so a negative HP in a log is
 * an overkill bug leaking into stored data rather than a legitimate value.
 */
export const BattleEventSchema = z.object({
  turn: PositiveIntSchema,
  actor: BattleActorSchema,
  type: BattleEventTypeSchema,
  amount: NonNegativeIntSchema,
  heroHp: NonNegativeIntSchema,
  enemyHp: NonNegativeIntSchema,
});

/**
 * Mirrors `BattleLog`.
 *
 * `events` may not be empty: a battle that produced no events did not happen, and storing
 * one would make the log unreplayable against the seed that supposedly produced it.
 */
export const BattleLogSchema = z.object({
  encounterId: NonEmptyStringSchema,
  seed: NonNegativeIntSchema,
  simVersion: NonEmptyStringSchema,
  events: z.array(BattleEventSchema).min(1, 'a battle log must contain at least one event'),
  outcome: BattleOutcomeSchema,
  turns: NonNegativeIntSchema,
});

/* -------------------------------------------------------------------------- *
 * Drift guards — the point of this file.
 *
 * If a schema and its hand-written interface ever disagree, `tsc` fails here. Nothing
 * below emits runtime code.
 * -------------------------------------------------------------------------- */

/** Fails to typecheck unless `Source` is assignable to `Target`. */
type AssertAssignable<Target, Source extends Target> = Source;

/**
 * zod infers optional fields as `foo?: T | undefined`, while the contract declares
 * `foo?: T` because `exactOptionalPropertyTypes` is on. The two describe the same runtime
 * shape, so the explicit `undefined` is stripped before comparing. This homomorphic
 * mapped type preserves the `?` modifier, so optional-vs-required drift is still caught.
 */
type NoExplicitUndefined<T> = { [K in keyof T]: Exclude<T[K], undefined> };

/** The contract-shaped view of what a schema parses to. */
type Parsed<Schema extends z.ZodTypeAny> = NoExplicitUndefined<z.infer<Schema>>;

/**
 * Mutual assignability, asserted per type and instantiated concretely — a generic
 * `Mirrors<C, S>` wrapper would defer the check and quietly assert nothing.
 *
 * A field missing from the schema, an extra field, a widened field type, or an
 * optional/required flip all break one of the two directions below.
 */
type _StatBlockMirrors = [
  AssertAssignable<StatBlock, Parsed<typeof StatBlockSchema>>,
  AssertAssignable<Parsed<typeof StatBlockSchema>, StatBlock>,
];

type _ActivityInputMirrors = [
  AssertAssignable<ActivityInput, Parsed<typeof ActivityInputSchema>>,
  AssertAssignable<Parsed<typeof ActivityInputSchema>, ActivityInput>,
];

type _EngineContextMirrors = [
  AssertAssignable<EngineContext, Parsed<typeof EngineContextSchema>>,
  AssertAssignable<Parsed<typeof EngineContextSchema>, EngineContext>,
];

type _HeroMirrors = [
  AssertAssignable<Hero, Parsed<typeof HeroSchema>>,
  AssertAssignable<Parsed<typeof HeroSchema>, Hero>,
];

type _RewardEntryMirrors = [
  AssertAssignable<RewardEntry, Parsed<typeof RewardEntrySchema>>,
  AssertAssignable<Parsed<typeof RewardEntrySchema>, RewardEntry>,
];

type _BattleEventMirrors = [
  AssertAssignable<BattleEvent, Parsed<typeof BattleEventSchema>>,
  AssertAssignable<Parsed<typeof BattleEventSchema>, BattleEvent>,
];

type _BattleLogMirrors = [
  AssertAssignable<BattleLog, Parsed<typeof BattleLogSchema>>,
  AssertAssignable<Parsed<typeof BattleLogSchema>, BattleLog>,
];

/* -------------------------------------------------------------------------- *
 * Typed boundary parsers.
 *
 * Convenience with a real purpose: because of `exactOptionalPropertyTypes`, assigning
 * `Schema.parse(body)` straight to its interface does NOT compile (zod's inferred
 * `foo?: T | undefined` is not assignable to the contract's `foo?: T`). These helpers do
 * that narrowing once, in the one place where the equivalence is proven by the drift
 * guards above, instead of every caller reaching for a cast.
 *
 * They throw `ZodError` like `parse` does. For a 400-response flow, use the schemas'
 * `safeParse` directly.
 * -------------------------------------------------------------------------- */

/** Parses untrusted input into an `ActivityInput`, or throws `ZodError`. */
export function parseActivityInput(input: unknown): ActivityInput {
  return ActivityInputSchema.parse(input) as ActivityInput;
}

/** Parses untrusted input into an `EngineContext`, or throws `ZodError`. */
export function parseEngineContext(input: unknown): EngineContext {
  return EngineContextSchema.parse(input) as EngineContext;
}

/** Parses untrusted input into a `Hero`, or throws `ZodError`. */
export function parseHero(input: unknown): Hero {
  return HeroSchema.parse(input) as Hero;
}

/** Parses untrusted input into a `RewardEntry`, or throws `ZodError`. */
export function parseRewardEntry(input: unknown): RewardEntry {
  return RewardEntrySchema.parse(input) as RewardEntry;
}

/** Parses untrusted input into a `BattleLog`, or throws `ZodError`. */
export function parseBattleLog(input: unknown): BattleLog {
  return BattleLogSchema.parse(input) as BattleLog;
}
